In [2]:
import numpy as np


In [3]:
n1 = np.array([1,2,3,4])
print(n1)
print(type(n1))


[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
x=[]
len(dir(n1))

165

In [5]:
n1.shape

(4,)

In [6]:
n2 = np.array([[1,2,3],[2,3,5]])
print(n2)
print(n2.shape)

[[1 2 3]
 [2 3 5]]
(2, 3)


creating matrix
- arange
- linespace
- random.rand
- random.randin
- eye
- ones
- zeroes 

In [7]:
np.arange(-10, 10, .2)

array([-1.00000000e+01, -9.80000000e+00, -9.60000000e+00, -9.40000000e+00,
       -9.20000000e+00, -9.00000000e+00, -8.80000000e+00, -8.60000000e+00,
       -8.40000000e+00, -8.20000000e+00, -8.00000000e+00, -7.80000000e+00,
       -7.60000000e+00, -7.40000000e+00, -7.20000000e+00, -7.00000000e+00,
       -6.80000000e+00, -6.60000000e+00, -6.40000000e+00, -6.20000000e+00,
       -6.00000000e+00, -5.80000000e+00, -5.60000000e+00, -5.40000000e+00,
       -5.20000000e+00, -5.00000000e+00, -4.80000000e+00, -4.60000000e+00,
       -4.40000000e+00, -4.20000000e+00, -4.00000000e+00, -3.80000000e+00,
       -3.60000000e+00, -3.40000000e+00, -3.20000000e+00, -3.00000000e+00,
       -2.80000000e+00, -2.60000000e+00, -2.40000000e+00, -2.20000000e+00,
       -2.00000000e+00, -1.80000000e+00, -1.60000000e+00, -1.40000000e+00,
       -1.20000000e+00, -1.00000000e+00, -8.00000000e-01, -6.00000000e-01,
       -4.00000000e-01, -2.00000000e-01, -3.55271368e-14,  2.00000000e-01,
        4.00000000e-01,  

In [8]:
y = np.linspace(1,5,25)
print(y)

[1.         1.16666667 1.33333333 1.5        1.66666667 1.83333333
 2.         2.16666667 2.33333333 2.5        2.66666667 2.83333333
 3.         3.16666667 3.33333333 3.5        3.66666667 3.83333333
 4.         4.16666667 4.33333333 4.5        4.66666667 4.83333333
 5.        ]


In [9]:
np.random.rand(3,3)

array([[0.31016191, 0.97610439, 0.63875802],
       [0.39122055, 0.10427264, 0.65732823],
       [0.56016386, 0.75932078, 0.01995992]])

In [10]:
np.random.randn(10)

array([ 0.30698249,  0.07320535,  0.41907824,  1.00988179,  0.86809099,
       -1.83620332,  0.2475365 ,  0.31686971, -0.17395153, -1.07262714])

In [11]:
np.random.randint(1,5,(5,5))

array([[3, 3, 2, 4, 3],
       [3, 3, 1, 2, 1],
       [2, 4, 3, 1, 1],
       [2, 1, 2, 3, 2],
       [3, 4, 2, 1, 4]])

In [12]:
x= np.random.randint(1,10,(3,2))
y= np.random.randint(1,10,(3,2))
print(x)
print(y)

[[2 7]
 [1 4]
 [2 8]]
[[8 4]
 [5 9]
 [6 6]]


In [13]:
x + y

array([[10, 11],
       [ 6, 13],
       [ 8, 14]])

In [14]:
x * y

array([[16, 28],
       [ 5, 36],
       [12, 48]])

In [15]:
np.sin(x)

array([[ 0.90929743,  0.6569866 ],
       [ 0.84147098, -0.7568025 ],
       [ 0.90929743,  0.98935825]])

In [16]:
print(x.sum())
print(x.mean())
print(x.std())

24
4.0
2.6457513110645907


In [18]:
x= np.random.randint(1,10,(10,10))
print(x)

[[8 1 9 3 5 5 5 1 6 4]
 [4 8 2 7 1 3 2 9 6 1]
 [7 3 2 8 9 6 2 6 5 1]
 [5 8 6 7 4 5 1 7 9 2]
 [2 3 3 1 5 8 1 1 8 8]
 [3 1 1 8 3 8 9 8 8 4]
 [9 3 6 4 2 8 7 5 1 6]
 [1 6 4 5 4 5 4 7 1 4]
 [8 9 8 7 6 5 7 8 2 6]
 [9 9 8 1 3 5 1 5 5 5]]


In [19]:
a= np.linspace(0,5,50)
print(a.shape)
a2=a.reshape(10,5)
print(a2)

(50,)
[[0.         0.10204082 0.20408163 0.30612245 0.40816327]
 [0.51020408 0.6122449  0.71428571 0.81632653 0.91836735]
 [1.02040816 1.12244898 1.2244898  1.32653061 1.42857143]
 [1.53061224 1.63265306 1.73469388 1.83673469 1.93877551]
 [2.04081633 2.14285714 2.24489796 2.34693878 2.44897959]
 [2.55102041 2.65306122 2.75510204 2.85714286 2.95918367]
 [3.06122449 3.16326531 3.26530612 3.36734694 3.46938776]
 [3.57142857 3.67346939 3.7755102  3.87755102 3.97959184]
 [4.08163265 4.18367347 4.28571429 4.3877551  4.48979592]
 [4.59183673 4.69387755 4.79591837 4.89795918 5.        ]]


In [22]:
print(x[0,0])
print(x[0,-1])
print(x[-1,0])
print(x[-1,-1])


8
4
9
5


In [26]:
print(x[0])
print(x[:3]) #first 3 rows
print(x[-3:]) #last 3 rows

[8 1 9 3 5 5 5 1 6 4]
[[8 1 9 3 5 5 5 1 6 4]
 [4 8 2 7 1 3 2 9 6 1]
 [7 3 2 8 9 6 2 6 5 1]]
[[1 6 4 5 4 5 4 7 1 4]
 [8 9 8 7 6 5 7 8 2 6]
 [9 9 8 1 3 5 1 5 5 5]]


In [29]:
x[:,2] #first column
x[:,-1] #last column
x[:,:3] #first 3 column
x[:,-3:] #last 3 column


array([[1, 6, 4],
       [9, 6, 1],
       [6, 5, 1],
       [7, 9, 2],
       [1, 8, 8],
       [8, 8, 4],
       [5, 1, 6],
       [7, 1, 4],
       [8, 2, 6],
       [5, 5, 5]])

In [31]:
print(x[:,[0,2,3,5]])

[[8 9 3 5]
 [4 2 7 3]
 [7 2 8 6]
 [5 6 7 5]
 [2 3 1 8]
 [3 1 8 8]
 [9 6 4 8]
 [1 4 5 5]
 [8 8 7 5]
 [9 8 1 5]]


filtering

In [32]:
x < 5 #boolean filter

array([[False,  True, False,  True, False, False, False,  True, False,
         True],
       [ True, False,  True, False,  True,  True,  True, False, False,
         True],
       [False,  True,  True, False, False, False,  True, False, False,
         True],
       [False, False, False, False,  True, False,  True, False, False,
         True],
       [ True,  True,  True,  True, False, False,  True,  True, False,
        False],
       [ True,  True,  True, False,  True, False, False, False, False,
         True],
       [False,  True, False,  True,  True, False, False, False,  True,
        False],
       [ True, False,  True, False,  True, False,  True, False,  True,
         True],
       [False, False, False, False, False, False, False, False,  True,
        False],
       [False, False, False,  True,  True, False,  True, False, False,
        False]])

In [33]:
x[x<5]

array([1, 3, 1, 4, 4, 2, 1, 3, 2, 1, 3, 2, 2, 1, 4, 1, 2, 2, 3, 3, 1, 1,
       1, 3, 1, 1, 3, 4, 3, 4, 2, 1, 1, 4, 4, 4, 1, 4, 2, 1, 3, 1])

In [34]:
x[(x>=3) & (x<=6) ]

array([3, 5, 5, 5, 6, 4, 4, 3, 6, 3, 6, 6, 5, 5, 6, 4, 5, 3, 3, 5, 3, 3,
       4, 3, 6, 4, 5, 6, 6, 4, 5, 4, 5, 4, 4, 6, 5, 6, 3, 5, 5, 5, 5])